# frozen_string_literal: true

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
plugin 'cocoapods-binary-cache'

config_cocoapods_binary_cache(
  cache_repo: {
    'default' => {
      'local' => 'prebuilt-frameworks'
    }
  },
  prebuild_config: 'Debug'
)

def binary_pod(name, *args)
  pod name, args, binary: true
end

target 'Example' do
  use_frameworks!

  binary_pod 'FSCalendar', '2.8.1'

  # Logger
  binary_pod 'SwiftyBeaver', '1.9.0'
end

inhibit_all_warnings!
